import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar/page";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { ThemeProvider } from "@/components/theme-provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Trackit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    
    <html lang="en" className="dark">
      <head>
        <title>Trackit</title>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>
        <div className="w-full h-16 flex justify-between items-center px-5 mb-4 z-50 fixed border-b-2 backdrop-blur-lg">
          <Link href="/">
            <Badge variant="outline">Trackit</Badge>
          </Link>

          <div>
            <Navbar />
          </div>
          <div>
            <Button className="mx-2">🌞</Button>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
